[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/*"  # 클라이언트에서 /api 경로로 오는 요청을
  to = "http://13.236.93.243:8001/api/:splat"  # Netlify Functions로 프록시
  status = 200
  force = true

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.jsx"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"