[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/Delivery/*"  # 클라이언트에서 /Delivery 경로로 들어오는 요청
  to = "http://13.236.93.243:8001/api/Delivery/:splat"  # API 서버로 프록시
  status = 200
  force = true

[[redirects]]
  from = "/reviewForm/*"  # 클라이언트에서 /reviewForm 경로로 들어오는 요청
  to = "http://13.236.93.243:8001/api/reviewForm/:splat"  # API 서버로 프록시
  status = 200
  force = true

[[redirects]]
  from = "/api/*"  # 나머지 /api 경로 처리
  to = "http://13.236.93.243:8001/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"  # 클라이언트 라우팅 처리
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.jsx"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"