import share1 from "../../assets/img/share1_1.jpg";
import share2 from "../../assets/img/share2_1.jpg";
import share3 from "../../assets/img/share3_1.jpg";
import share4 from "../../assets/img/share4_1.jpg";
import share5 from "../../assets/img/share5_1.jpg";

export const dummyData = {
  desk: [
    {
      id: 1,
      img: share1,
      name: "Rustic Oak Dining Table",
      category: "desk",
      location: "WoodCraft Studio",
      cost: "100만원",
      price: "25만원",
      reason: "테이블 표면에 긁힘",
      size: [1200, 800, 700],
    },
    {
      id: 2,
      img: share2,
      name: "Handmade Maple Desk",
      category: "desk",
      location: "TimberWorks",
      cost: "120만원",
      price: "45만원",
      reason: "모서리 부분 칩",
      size: [1300, 750, 750],
    },
    {
      id: 3,
      img: share3,
      name: "Minimalist Modern Desk",
      category: "desk",
      location: "ModernMakers",
      cost: "80만원",
      price: "35만원",
      reason: "미세한 흠집",
      size: [1100, 700, 730],
    },
    {
      id: 4,
      img: share4,
      name: "Industrial Steel Desk",
      category: "desk",
      location: "Urban Designs",
      cost: "90만원",
      price: "40만원",
      reason: "상판에 얼룩",
      size: [1400, 800, 760],
    },
    {
      id: 5,
      img: share5,
      name: "Sleek Black Desk",
      category: "desk",
      location: "OfficePro",
      cost: "75만원",
      price: "30만원",
      reason: "미세한 스크래치",
      size: [1200, 700, 710],
    },
    {
      id: 6,
      img: share1,
      name: "Vintage Oak Desk",
      category: "desk",
      location: "Antique Studio",
      cost: "150만원",
      price: "70만원",
      reason: "오래된 마감 불량",
      size: [1400, 750, 780],
    },
    {
      id: 7,
      img: share2,
      name: "Executive Mahogany Desk",
      category: "desk",
      location: "Classic Designs",
      cost: "200만원",
      price: "90만원",
      reason: "모서리 부분 약간 손상",
      size: [1600, 850, 800],
    },
    {
      id: 8,
      img: share3,
      name: "Compact Study Desk",
      category: "desk",
      location: "HomeStudios",
      cost: "60만원",
      price: "25만원",
      reason: "스크래치 일부",
      size: [1000, 600, 720],
    },
    {
      id: 9,
      img: share4,
      name: "Custom Handmade Desk",
      category: "desk",
      location: "CustomWorks",
      cost: "180만원",
      price: "75만원",
      reason: "상판 불균형",
      size: [1500, 750, 740],
    },
    {
      id: 10,
      img: share5,
      name: "Simple White Desk",
      category: "desk",
      location: "Minimalist Studios",
      cost: "85만원",
      price: "38만원",
      reason: "흠집이 약간 있음",
      size: [1300, 750, 760],
    },
  ],
  chair: [
    {
      id: 1,
      img: share2,
      name: "Ergonomic Office Chair",
      category: "chair",
      location: "WorkComfort",
      cost: "30만원",
      price: "15만원",
      reason: "사용 흔적 있음",
      size: [600, 600, 1100],
    },
    {
      id: 2,
      img: share3,
      name: "Modern Lounge Chair",
      category: "chair",
      location: "Lounge Creations",
      cost: "50만원",
      price: "25만원",
      reason: "조금 흔들림 있음",
      size: [700, 750, 900],
    },
    {
      id: 3,
      img: share4,
      name: "Vintage Leather Chair",
      category: "chair",
      location: "Classic Chairs",
      cost: "150만원",
      price: "70만원",
      reason: "약간의 가죽 벗겨짐",
      size: [650, 700, 1050],
    },
    {
      id: 4,
      img: share5,
      name: "Adjustable Gaming Chair",
      category: "chair",
      location: "Gamer's Haven",
      cost: "120만원",
      price: "60만원",
      reason: "사용 흔적 약간",
      size: [700, 750, 1200],
    },
    {
      id: 5,
      img: share1,
      name: "Executive Office Chair",
      category: "chair",
      location: "OfficeMaster",
      cost: "110만원",
      price: "50만원",
      reason: "등받이 부분 살짝 손상",
      size: [650, 700, 1100],
    },
    {
      id: 6,
      img: share2,
      name: "Task Office Chair",
      category: "chair",
      location: "WorkHub",
      cost: "70만원",
      price: "30만원",
      reason: "조금 흔들림 있음",
      size: [650, 650, 1050],
    },
    {
      id: 7,
      img: share3,
      name: "Swivel Chair with Armrests",
      category: "chair",
      location: "ComfortLounge",
      cost: "80만원",
      price: "40만원",
      reason: "미세한 기울기 있음",
      size: [700, 700, 1100],
    },
    {
      id: 8,
      img: share4,
      name: "Leather Office Chair",
      category: "chair",
      location: "OfficeStyle",
      cost: "90만원",
      price: "45만원",
      reason: "가죽 부분 살짝 벗겨짐",
      size: [600, 650, 1000],
    },
    {
      id: 9,
      img: share5,
      name: "Mesh Office Chair",
      category: "chair",
      location: "MeshWorks",
      cost: "60만원",
      price: "25만원",
      reason: "패브릭 재질 손상",
      size: [650, 650, 1050],
    },
    {
      id: 10,
      img: share1,
      name: "Comfort Chair with Headrest",
      category: "chair",
      location: "ComfortZone",
      cost: "100만원",
      price: "50만원",
      reason: "사용 흔적 약간",
      size: [700, 700, 1150],
    },
  ],
  expendables: [
    {
      id: 1,
      img: share4,
      name: "Office Supplies Pack",
      category: "expendables",
      location: "OfficeMax",
      cost: "10만원",
      price: "5만원",
      reason: "상태 양호",
      size: [200, 200, 50],
    },
    {
      id: 2,
      img: share5,
      name: "Notebook Refill Papers",
      category: "expendables",
      location: "PaperWorks",
      cost: "3만원",
      price: "1만원",
      reason: "새것",
      size: [150, 100, 10],
    },
    {
      id: 3,
      img: share1,
      name: "Ink Cartridge Set",
      category: "expendables",
      location: "InkWorld",
      cost: "15만원",
      price: "7만원",
      reason: "미사용",
      size: [120, 80, 50],
    },
    {
      id: 4,
      img: share2,
      name: "Post-It Notes Pack",
      category: "expendables",
      location: "Stationery Co.",
      cost: "2만원",
      price: "1만원",
      reason: "새것",
      size: [150, 100, 20],
    },
    {
      id: 5,
      img: share3,
      name: "File Folders Set",
      category: "expendables",
      location: "Office Supplies Hub",
      cost: "5만원",
      price: "2만원",
      reason: "상태 양호",
      size: [250, 150, 30],
    },
    {
      id: 6,
      img: share4,
      name: "Whiteboard Markers",
      category: "expendables",
      location: "OfficeGoods",
      cost: "1만원",
      price: "5000원",
      reason: "새것",
      size: [100, 100, 10],
    },
    {
      id: 7,
      img: share5,
      name: "Scissors Set",
      category: "expendables",
      location: "CraftCo",
      cost: "3만원",
      price: "1만5000원",
      reason: "새것",
      size: [200, 100, 30],
    },
    {
      id: 8,
      img: share1,
      name: "Stapler Set",
      category: "expendables",
      location: "OfficeEssentials",
      cost: "5만원",
      price: "2만5000원",
      reason: "상태 양호",
      size: [200, 150, 50],
    },
    {
      id: 9,
      img: share2,
      name: "Printer Paper Pack",
      category: "expendables",
      location: "PaperCo",
      cost: "7만원",
      price: "3만원",
      reason: "새것",
      size: [250, 150, 50],
    },
    {
      id: 10,
      img: share3,
      name: "Binder Clips Set",
      category: "expendables",
      location: "Staples World",
      cost: "1만원",
      price: "5000원",
      reason: "새것",
      size: [100, 100, 30],
    },
  ],
  table: [
    {
      id: 1,
      img: share1,
      name: "Rustic Oak Dining Table",
      category: "table",
      location: "WoodCraft Studio",
      cost: "100만원",
      price: "25만원",
      reason: "테이블 표면에 긁힘",
      size: [1200, 800, 700],
    },
    {
      id: 2,
      img: share2,
      name: "Handmade Modern Table",
      category: "table",
      location: "HandyWorks",
      cost: "85만원",
      price: "30만원",
      reason: "다리 부분 색바램",
      size: [1100, 750, 720],
    },
    {
      id: 3,
      img: share3,
      name: "Rustic Pine Coffee Table",
      category: "table",
      location: "Rustic Touch",
      cost: "90만원",
      price: "35만원",
      reason: "모서리 마감 불량",
      size: [1000, 600, 720],
    },
    {
      id: 4,
      img: share4,
      name: "Vintage Cherry Wood Table",
      category: "table",
      location: "Vintage Works",
      cost: "120만원",
      price: "40만원",
      reason: "스크래치와 작은 찌그러짐",
      size: [1300, 900, 750],
    },
    {
      id: 5,
      img: share5,
      name: "Eco-Friendly Bamboo Table",
      category: "table",
      location: "EcoWood Studio",
      cost: "95만원",
      price: "20만원",
      reason: "색상 맞춤 실패",
      size: [1250, 700, 740],
    },
    {
      id: 6,
      img: share1,
      name: "Reclaimed Wood Table",
      category: "table",
      location: "EcoCraft",
      cost: "110만원",
      price: "45만원",
      reason: "모서리 부분 손상",
      size: [1300, 800, 750],
    },
    {
      id: 7,
      img: share2,
      name: "Glass Top Dining Table",
      category: "table",
      location: "Modern Style",
      cost: "140만원",
      price: "60만원",
      reason: "상판에 스크래치",
      size: [1200, 900, 700],
    },
    {
      id: 8,
      img: share3,
      name: "Marble Coffee Table",
      category: "table",
      location: "Luxury Design",
      cost: "250만원",
      price: "120만원",
      reason: "흠집 일부",
      size: [1000, 600, 700],
    },
    {
      id: 9,
      img: share4,
      name: "Contemporary Wooden Table",
      category: "table",
      location: "WoodWorks",
      cost: "85만원",
      price: "35만원",
      reason: "표면 색상 차이",
      size: [1200, 800, 750],
    },
    {
      id: 10,
      img: share5,
      name: "Round Oak Dining Table",
      category: "table",
      location: "Classic Tables",
      cost: "120만원",
      price: "50만원",
      reason: "다리 부분 손상",
      size: [1000, 1000, 750],
    },
  ],
  etc: [
    {
      id: 1,
      img: share3,
      name: "Decorative Plant",
      category: "etc",
      location: "HomeDecor",
      cost: "15만원",
      price: "7만원",
      reason: "식물 잎 몇 개 손상",
      size: [400, 400, 600],
    },
    {
      id: 2,
      img: share4,
      name: "Antique Mirror",
      category: "etc",
      location: "Vintage Finds",
      cost: "50만원",
      price: "20만원",
      reason: "액자 부분 약간 손상",
      size: [800, 1200, 50],
    },
    {
      id: 3,
      img: share5,
      name: "Decorative Vase",
      category: "etc",
      location: "VaseWorld",
      cost: "20만원",
      price: "10만원",
      reason: "미세한 금이 갔음",
      size: [350, 350, 450],
    },
    {
      id: 4,
      img: share1,
      name: "Classic Wall Clock",
      category: "etc",
      location: "Timepieces Ltd.",
      cost: "30만원",
      price: "15만원",
      reason: "시계 부분 약간의 흠집",
      size: [300, 300, 100],
    },
    {
      id: 5,
      img: share2,
      name: "Retro Desk Lamp",
      category: "etc",
      location: "LightWorks",
      cost: "40만원",
      price: "18만원",
      reason: "약간의 녹슨 흔적",
      size: [350, 350, 600],
    },
    {
      id: 6,
      img: share3,
      name: "Tabletop Organizer",
      category: "etc",
      location: "OrganizeIt",
      cost: "10만원",
      price: "5만원",
      reason: "상태 양호",
      size: [250, 150, 300],
    },
    {
      id: 7,
      img: share4,
      name: "Brass Candleholder",
      category: "etc",
      location: "Candle Creations",
      cost: "15만원",
      price: "7만원",
      reason: "미세한 기스 있음",
      size: [150, 150, 300],
    },
    {
      id: 8,
      img: share5,
      name: "Small Ceramic Pot",
      category: "etc",
      location: "CeramicsStudio",
      cost: "8만원",
      price: "3만원",
      reason: "미세한 손상 있음",
      size: [200, 200, 250],
    },
    {
      id: 9,
      img: share1,
      name: "Vintage Picture Frame",
      category: "etc",
      location: "OldWorld",
      cost: "5만원",
      price: "2만원",
      reason: "액자에 약간의 흔적",
      size: [300, 400, 50],
    },
    {
      id: 10,
      img: share2,
      name: "Hanging Wall Shelf",
      category: "etc",
      location: "Home Decor",
      cost: "40만원",
      price: "20만원",
      reason: "사용 흔적 있음",
      size: [600, 200, 300],
    },
  ],
};

export default dummyData;
